### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by shikulja** [mistydemeo/lunardata#5]
1. I could not find out where the font of the psx version is located
2. More information about the text. Maximum length of text in the game for different versions

**Comment by mistydemeo** [comment]
1. I believe it's contained in `SYSTEM.DAT`, like the Saturn version. It's in a different format since it's a 1-bit font instead of a 2-bit font. Do you need a copy? I have something I extracted from RAM awhile back.
2. I'm actually not sure what the maximum text length is. With the control codes changed appropriately, there's no reason it has to be the same length as the original. You're probably limited by RAM, which is going to be system-dependent. (e.g. you could probably have a *lot* more text on the Windows version)

Mind if I ask what you're doing and what you need this for?

**Comment by shikulja** [comment]
Thanks, I found SYSTEM.DAT
I also found sss_fontbuild there is some useful information, unfortunately I cannot extract the text with this utility, since I have windows, and it may not work at all.
Need to look for other ways to extract the font image

I'm still trying to insert a script, for this need to add new symbols to the table in order to encode it. To do this, first need to draw characters in the font.

**Comment by mistydemeo** [comment]
If you have the Rust compiler, you can use `sss_fontbuild` on Windows just fine! However, it only supports the Saturn version, and it *builds* a font - it doesn't extract it.

> I'm still trying to insert a script, for this need to add new symbols to the table in order to encode it. To do this, first need to draw characters in the font.

I see, that makes sense. What language are you using? I'm afraid most of my work has been focused on translating the Saturn version, not the PS1 or Windows versions, but most of it is the same.

The PS1 and Windows script uses a slightly different format, but it's very similar. The biggest problem is that `SYSTEM.DAT` is compressed on PS1 and Windows, and I haven't done anything to support decompressing it yet. That file contains the font and the system text, so you do need to figure that out in order to be able to translate something.

**Comment by shikulja** [comment]
@mistydemeo Thank you, now everything is clear.
It seems that I started translating early, this is my favorite game, and unfortunately no one has translated it into Russian in 20 years. So I thought I could do it myself, but unfortunately, the tools are not yet ready for a full-fledged translation.
I'll leave it for later

ps. I will throw off text1, maybe it will be useful for you to check. Cyrillic letters [А-Я] [а-я] 36 + 36 = 72 should be entered into the table.
Perhaps the text will still need to be corrected, since I do not know what the maximum length of the text is, I tried to keep within 40 characters.
[SCRIPT.zip](https://github.com/studio-lucia/lunardata/files/7133559/SCRIPT.zip)
So far, I just noticed that formatting the text manually is not very convenient.
